### ISSUE TITLE
ErrorCode

### ISSUE THREAD

**Issue by emersonbottero** [belset/FlatValidator#43]
I'm trying to replace fluentvalidation on my project, so far so good but I'm missing the return ErrorCode options.. 
I use it to set the response to 403 when someone try to edit a entry created by another user.

**Comment by belset** [comment]
It looks like functionality of the 'Metadata' may be useful in this case. Agreed, the spec is too short but let me just refer to that - 

> Using MetaData can extend functionality and can help to return certain data beyond the validator:
> ```js
> var result = FlatValidator.Validate(model, v =>
> {
>     v.MetaData["ValidationTime"] = DateTime.UtcNow.ToString();
>     // ....
> });
> 
> return result.MetaData["ValidationTime"]; // access to the MetaData value outside of the validation
> ```
> 

Also some additional examples of usage may be found in the file [MetaDataTests.cs](https://github.com/belset/FlatValidator/blob/main/src/FlatValidator.Tests/MetaDataTests.cs)
